vim.o.autoindent = true
vim.o.cursorline = true -- highlight current line
vim.o.expandtab = true -- convert tabs to spaces
vim.o.hidden = true -- allow buffers to be hidden w/o saving
vim.o.hlsearch = true -- highlight matches
vim.o.ignorecase = true -- ignore case for searching
vim.o.incsearch = true -- search as characters are entered
vim.o.listchars= "tab:>-,extends:>"
vim.o.modeline = true -- allow modelines
vim.o.modelines= 1 -- only allow one modeline
vim.o.mouse = ""
vim.o.wrap = false
vim.o.number = true -- turn line numbers on
vim.o.scrolloff = 15 -- lines above and below cursor when scrolling
vim.o.shiftwidth = 2 -- number of spaces to indent
vim.o.splitright = true
vim.o.sts = 2 -- number of spaces pressing tab is equal to
vim.o.smartcase = true -- search with capital letters
vim.o.smartindent = true
-- vim.o.swapfile = false
vim.o.ts = 2 -- number of spaces a tab is made up of
vim.o.wildmenu = true -- visual command autocomple
